services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=bankdb'
      - 'POSTGRES_PASSWORD=rootadmin'
      - 'POSTGRES_USER=rootadmin'
    ports:
      - '5432:5432'
    restart: 'always'

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8081:8080'
    container_name: 'backend_transaction'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/bankdb
      - SPRING_DATASOURCE_USERNAME=rootadmin
      - SPRING_DATASOURCE_PASSWORD=rootadmin
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - postgres
